name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
      - name: Run Test
        if: always()
        run: mvn clean test
        continue-on-error: true
      - name: Copy History
        uses: actions/checkout@v2
        if: always()
        with:
          ref: main
          path: main
      - name: Build Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history
          keep_reports: 20
      - name: Publish Report
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: main
          PUBLISH_DIR: allure-history


